# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.7
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_min_max_sum', [dirname(__file__)])
        except ImportError:
            import _min_max_sum
            return _min_max_sum
        if fp is not None:
            try:
                _mod = imp.load_module('_min_max_sum', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _min_max_sum = swig_import_helper()
    del swig_import_helper
else:
    import _min_max_sum
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class MMS(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, MMS, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MMS, name)
    __repr__ = _swig_repr
    __swig_getmethods__["mms_t"] = lambda x: _min_max_sum.MMS_mms_t
    if _newclass:
        mms_t = staticmethod(_min_max_sum.MMS_mms_t)
    __swig_getmethods__["mms_a"] = lambda x: _min_max_sum.MMS_mms_a
    if _newclass:
        mms_a = staticmethod(_min_max_sum.MMS_mms_a)

    def __init__(self):
        this = _min_max_sum.new_MMS()
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _min_max_sum.delete_MMS
    __del__ = lambda self: None
MMS_swigregister = _min_max_sum.MMS_swigregister
MMS_swigregister(MMS)

def MMS_mms_t(arg2):
    return _min_max_sum.MMS_mms_t(arg2)
MMS_mms_t = _min_max_sum.MMS_mms_t

def MMS_mms_a(out, arg3):
    return _min_max_sum.MMS_mms_a(out, arg3)
MMS_mms_a = _min_max_sum.MMS_mms_a

# This file is compatible with both classic and new-style classes.


